FROM debian:stretch-slim
MAINTAINER Bryan J Rodriguez <bryan.j.rodriguez@intel.com>, John Belstner <john.belstner@intel.com>
  
RUN apt update && apt install -yq --no-install-recommends \
  avahi-daemon \
  avahi-utils \
  dumb-init \
  && apt clean
	
WORKDIR /

ENTRYPOINT ["dumb-init"]
CMD ["/usr/sbin/avahi-daemon", "--no-drop-root"]
